volumes:
  ldap_data:
  ldap_config:

secrets:
  slapd_password:
    file: ./secrets/slapd_password.txt
  geoserver_privileged_user_passwd:
    file: ./secrets/geoserver_privileged_user_passwd.txt

services:
  ldap:
    image: georchestra/ldap:24.0.x
    secrets:
      - slapd_password
      - geoserver_privileged_user_passwd
    environment:
      - SLAPD_ORGANISATION=georchestra
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_PASSWORD_FILE=/run/secrets/slapd_password
      - SLAPD_PASSWORD=
      - GEOSERVER_PRIVILEGED_USER_PASSWORD_FILE=/run/secrets/geoserver_privileged_user_passwd
      - SLAPD_LOG_LEVEL=32768 # See https://www.openldap.org/doc/admin24/slapdconfig.html#loglevel%20%3Clevel%3E
      - RUN_AS_UID=0
      - RUN_AS_GID=0
      - LDAPHOST=localhost # needed for container to start correctly, DO NOT REMOVE
    env_file:
      - .envs-ldap
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
    restart: always
    ports:
      - "389:389"
